name: ServerGuard
api-version: 1.16
main: live.chanakancloud.serverguard.Anticheat
version: 1.0
author: Chanakan Mungtin
commands:
  anticheat:
    aliases: [ac]
    description: "The main command for the Anticheat framework"
